download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/zjleblanc-windows-1.0.1.tar.gz
format_version: 1.0.0
name: windows
namespace: zjleblanc
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/zjleblanc/windows/versions/1.0.1/
